blank_issues_enabled: false
contact_links:
  - name: Anti-Pattern Coaching Support
    url: https://github.com/kesslerio/mcp-code-reviewer/discussions
    about: Community discussions for general questions and support
EOF < /dev/null