name: Claude Issue Triage

on:
  issues:
    types: [opened]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  triage-issue:
    name: Claude-assisted issue triage
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
      issues: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup GitHub MCP Server
        run: |
          mkdir -p /tmp/mcp-config
          cat > /tmp/mcp-config/mcp-servers.json << 'EOF'
          {
            "github": {
              "command": "docker",
              "args": [
                "run",
                "-i",
                "--rm",
                "-e",
                "GITHUB_PERSONAL_ACCESS_TOKEN",
                "ghcr.io/github/github-mcp-server:sha-7aced2b"
              ],
              "env": {
                "GITHUB_PERSONAL_ACCESS_TOKEN": "${{ secrets.GITHUB_TOKEN }}"
              }
            }
          }
          EOF

      - name: Set issue number environment variable
        run: echo "ISSUE_NUMBER=${{ github.event.issue.number }}" >> $GITHUB_ENV

      - run: claude -p "/project:triage" --mcp-config /tmp/mcp-config/mcp-servers.json --allowedTools "Bash(gh label list)" "mcp__github__get_issue" "mcp__github__get_issue_comments" "mcp__github__update_issue" "mcp__github__search_issues" "mcp__github__list_issues"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}