name: Claude Lint

on: pull_request

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-claude:
    name: Claude-assisted code linting
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - run: claude -p "/project:lint" --allowedTools "Bash(git log:*)" "Bash(git diff:*)" "Bash(git status:*)"